import './methods/expressions/ArrayExpression.ts'
import './methods/expressions/ArrowFunctionExpression.ts'
import './methods/expressions/AwaitExpression.ts'
import './methods/expressions/BinaryExpression.ts'
import './methods/expressions/CallExpression.ts'
import './methods/expressions/ClassDeclaration.ts'
import './methods/expressions/FunctionExpression.ts'
import './methods/expressions/Identifier.ts'
import './methods/expressions/Literal.ts'
import './methods/expressions/MemberExpression copy.ts'
import './methods/expressions/MemberExpression.ts'
import './methods/expressions/MetaProperty.ts'
import './methods/expressions/NewExpression.ts'
import './methods/expressions/ObjectExpression.ts'
import './methods/expressions/PrivateIdentifier.ts'
import './methods/expressions/TemplateLiteral.ts'
import './methods/objectElements/Property.ts'
import './methods/statements/BlockStatement.ts'
import './methods/statements/BreakStatement.ts'
import './methods/statements/ElseStatement.ts'
import './methods/statements/ExpressionStatement.ts'
import './methods/statements/ForOfStatement.ts'
import './methods/statements/FunctionDeclaration.ts'
import './methods/statements/IfStatement.ts'
import './methods/statements/ImportDeclaration.ts'
import './methods/statements/ReturnStatement.ts'
import './methods/statements/SwitchStatement.ts'
import './methods/statements/VariableDeclaration.ts'

export * from './types/index.js'
export * from './transformers/index.js'
export * from './libs/index.js'
export * from './class/index.js'

import './transformers/index.js'
import './cli.js'
